GODOT_URL=https://github.com/zilongpa/godot.git
GODOT_BRANCH=30ccda47f9980e47a7e1cd9c19943ab2a54362f4
GODOT_CPP_URL=https://github.com/godotengine/godot-cpp.git
GODOT_CPP_BRANCH=507ed9d840c01a3c5b2a39af8bb4000bfac30bf5
