GODOT_URL=https://github.com/zilongpa/godot.git
GODOT_BRANCH=7461176899de3305712ea1a72213bfe2cbcebbde
GODOT_CPP_URL=https://github.com/godotengine/godot-cpp.git
GODOT_CPP_BRANCH=507ed9d840c01a3c5b2a39af8bb4000bfac30bf5
