GODOT_URL=https://github.com/zilongpa/godot.git
GODOT_BRANCH=0c26e3d670aab646f29df855863a9a19e9760428
GODOT_CPP_URL=https://github.com/godotengine/godot-cpp.git
GODOT_CPP_BRANCH=507ed9d840c01a3c5b2a39af8bb4000bfac30bf5
